name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint import
        run: python -c "import fastapi, uvicorn, pydantic; print('ok')"
      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: false

  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install deps
        run: npm ci
      - name: Build
        run: npm run build
        env:
          VITE_API_BASE_URL: http://localhost:8000
      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: false

